<?php

declare(strict_types=1);

namespace App\Message;

use Symfony\Component\Messenger\Attribute\AsMessage;

/**
 * Carries an AI instruction from the HTTP request to the async worker.
 *
 * The worker reads the selected provider and model from the database, calls the
 * LLM, streams tokens to a Mercure topic, and publishes a final "done" or "error"
 * event so the browser can end the request.
 */
#[AsMessage]
final readonly class AiInstructionMessage
{
    /**
     * @param string $topic       Mercure topic to publish streamed tokens to
     * @param string $requestId   id generated by the browser, echoed in every event
     * @param string $instruction the user's prompt or suggestion prompt
     * @param string $document    full document markdown (for context)
     * @param string $selection   selected text (empty if no selection)
     */
    public function __construct(
        public string $topic,
        public string $requestId,
        public string $instruction,
        public string $document,
        public string $selection = '',
    ) {
    }
}
